var virsi=
[
  {"tag":"div","class":"dus__list","children":[
      {"tag":"ul","children":[
          {"tag":"li","class":"dus__list__item dus__list__item--13","children":[
              {"tag":"a","class":"map-link","id":"dus_32","href":"http://www.virsia.lv/lv/uzpildes-stacijas/#dus/32","data-contacts":"Somersētas iela 11a, Aglona, LV-5304<br ></a>
Tālr.:+371 65381233<br />
Darba laiks: 06:00 - 23:00<br />
","data-fuels":"[{"name":"95E","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/1\/Virsi-A_ikonas_-01.svg"},{"name":"98","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/2\/Virsi-A_ikonas_-02.svg"},{"name":"DD","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/3\/Virsi-A_ikonas_-03.svg"},{"name":"AD","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/4\/Virsi-A_ikonas_-04.svg"},{"name":"WC","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/7\/Virsi-A_ikonas_-07.svg"},{"name":"Veikals","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/8\/Virsi-A_ikonas_-08.svg"},{"name":"Kafija","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/9\/Virsi-A_ikonas_-09.svg"},{"name":"Uzkodas","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/10\/Virsi-A_ikonas_-10.svg"},{"name":"WiFi","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/13\/Virsi-A_ikonas_-13.svg"},{"name":"Gaiss","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/14\/Virsi-A_ikonas_-14.svg"},{"name":"\u016adens","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/16\/Virsi-A_ikonas_-16.svg"}]","data-lng":"27.003878100000065","data-lat":"56.1358957","children":[
                  {"tag":"span","class":"title","html":"DUS "Aglona""}
                ]}
            ]},
          {"tag":"li","class":"dus__list__item dus__list__item--14","children":[
              {"tag":"a","class":"map-link","id":"dus_3","href":"http://www.virsia.lv/lv/uzpildes-stacijas/#dus/3","data-contacts":"Rīgas iela 11, Alūksne, LV-4301<br ></a>
Tālr.:+371 64381110<br />
Darba laiks: 00:00 - 24:00","data-fuels":"[{"name":"95E","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/1\/Virsi-A_ikonas_-01.svg"},{"name":"98","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/2\/Virsi-A_ikonas_-02.svg"},{"name":"DD","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/3\/Virsi-A_ikonas_-03.svg"},{"name":"AD","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/4\/Virsi-A_ikonas_-04.svg"},{"name":"G","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/5\/Virsi-A_ikonas_-06.svg"},{"name":"AD Blue","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/6\/Virsi-A_ikonas_-05.svg"},{"name":"WC","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/7\/Virsi-A_ikonas_-07.svg"},{"name":"Veikals","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/8\/Virsi-A_ikonas_-08.svg"},{"name":"Kafija","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/9\/Virsi-A_ikonas_-09.svg"},{"name":"Uzkodas","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/10\/Virsi-A_ikonas_-10.svg"},{"name":"WiFi","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/13\/Virsi-A_ikonas_-13.svg"},{"name":"\u016adens","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/16\/Virsi-A_ikonas_-16.svg"},{"name":"Piekabju noma","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/17\/Virsi-A_ikonas_-17.svg"},{"name":"BioDD","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/19\/Virsi-A_bioDD.svg"}]","data-lng":"27.02109489999998","data-lat":"57.4305819","children":[
                  {"tag":"span","class":"title","html":"DUS "Alūksne""}
                ]}
            ]},
          {"tag":"li","class":"dus__list__item dus__list__item--52","children":[
              {"tag":"a","class":"map-link","id":"dus_5","href":"http://www.virsia.lv/lv/uzpildes-stacijas/#dus/5","data-contacts":"“Asni”, Gauja, Inčukalna pag., Inčukalna nov., LV-2140<br ></a>
Tālr.:+371 67977921<br />
Darba laiks: 00:00 - 24:00","data-fuels":"[{"name":"95E","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/1\/Virsi-A_ikonas_-01.svg"},{"name":"98","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/2\/Virsi-A_ikonas_-02.svg"},{"name":"DD","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/3\/Virsi-A_ikonas_-03.svg"},{"name":"AD","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/4\/Virsi-A_ikonas_-04.svg"},{"name":"AD Blue","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/6\/Virsi-A_ikonas_-05.svg"},{"name":"WC","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/7\/Virsi-A_ikonas_-07.svg"},{"name":"Veikals","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/8\/Virsi-A_ikonas_-08.svg"},{"name":"Kafija","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/9\/Virsi-A_ikonas_-09.svg"},{"name":"Uzkodas","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/10\/Virsi-A_ikonas_-10.svg"},{"name":"WiFi","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/13\/Virsi-A_ikonas_-13.svg"},{"name":"Gaiss","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/14\/Virsi-A_ikonas_-14.svg"},{"name":"\u016adens","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/16\/Virsi-A_ikonas_-16.svg"},{"name":"Piekabju noma","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/17\/Virsi-A_ikonas_-17.svg"}]","data-lng":"24.703981399999975","data-lat":"57.1269677","children":[
                  {"tag":"span","class":"title","html":"DUS "Asni""}
                ]}
            ]},
          {"tag":"li","class":"dus__list__item dus__list__item--1","children":[
              {"tag":"a","class":"map-link","id":"dus_46","href":"http://www.virsia.lv/lv/uzpildes-stacijas/#dus/46","data-contacts":"Rīgas gatve 45, Ādaži, LV-2164<br ></a>
Tālr.:+371 67996353<br />
Darba laiks: 00:00 - 24:00<br />
","data-fuels":"[{"name":"95E","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/1\/Virsi-A_ikonas_-01.svg"},{"name":"98","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/2\/Virsi-A_ikonas_-02.svg"},{"name":"DD","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/3\/Virsi-A_ikonas_-03.svg"},{"name":"G","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/5\/Virsi-A_ikonas_-06.svg"},{"name":"AD Blue","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/6\/Virsi-A_ikonas_-05.svg"},{"name":"WC","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/7\/Virsi-A_ikonas_-07.svg"},{"name":"Veikals","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/8\/Virsi-A_ikonas_-08.svg"},{"name":"Kafija","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/9\/Virsi-A_ikonas_-09.svg"},{"name":"Uzkodas","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/10\/Virsi-A_ikonas_-10.svg"},{"name":"Auto mazg\u0101tavu","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/11\/Virsi-A_ikonas_-11.svg"},{"name":"WiFi","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/13\/Virsi-A_ikonas_-13.svg"},{"name":"Gaiss","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/14\/Virsi-A_ikonas_-14.svg"},{"name":"\u016adens","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/16\/Virsi-A_ikonas_-16.svg"},{"name":"Piekabju noma","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/17\/Virsi-A_ikonas_-17.svg"}]","data-lng":"24.318116000000032","data-lat":"57.078741","children":[
                  {"tag":"span","class":"title","html":"DUS "Ādaži""}
                ]}
            ]},
          {"tag":"li","class":"dus__list__item dus__list__item--1","children":[
              {"tag":"a","class":"map-link","id":"dus_63","href":"http://www.virsia.lv/lv/uzpildes-stacijas/#dus/63","data-contacts":"Uzvaras bulvāris 16, Rīga, LV-1048<br ></a>
Tālr.: +371 67704991<br />
Darba laiks: 00:00 - 24:00","data-fuels":"[{"name":"95E","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/1\/Virsi-A_ikonas_-01.svg"},{"name":"98","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/2\/Virsi-A_ikonas_-02.svg"},{"name":"DD","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/3\/Virsi-A_ikonas_-03.svg"},{"name":"WC","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/7\/Virsi-A_ikonas_-07.svg"},{"name":"Veikals","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/8\/Virsi-A_ikonas_-08.svg"},{"name":"Kafija","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/9\/Virsi-A_ikonas_-09.svg"},{"name":"Uzkodas","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/10\/Virsi-A_ikonas_-10.svg"},{"name":"Auto mazg\u0101tavu","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/11\/Virsi-A_ikonas_-11.svg"},{"name":"Pay with cards","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/12\/Virsi-A_ikonas_-12.svg"},{"name":"WiFi","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/13\/Virsi-A_ikonas_-13.svg"},{"name":"Gaiss","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/14\/Virsi-A_ikonas_-14.svg"},{"name":"\u016adens","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/16\/Virsi-A_ikonas_-16.svg"},{"name":"Piekabju noma","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/17\/Virsi-A_ikonas_-17.svg"}]","data-lng":"24.089682100000004","data-lat":"56.9383954","children":[
                  {"tag":"span","class":"title","html":"DUS "Arkādijs""}
                ]}
            ]},
          {"tag":"li","class":"dus__list__item dus__list__item--17","children":[
              {"tag":"a","class":"map-link","id":"dus_33","href":"http://www.virsia.lv/lv/uzpildes-stacijas/#dus/33","data-contacts":"Krasta iela 3, Balvi, LV-4501<br ></a>
Tālr.: +371 64522064<br />
Darba laiks: 06:00 - 23:00<br />
","data-fuels":"[{"name":"95E","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/1\/Virsi-A_ikonas_-01.svg"},{"name":"98","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/2\/Virsi-A_ikonas_-02.svg"},{"name":"DD","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/3\/Virsi-A_ikonas_-03.svg"},{"name":"AD","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/4\/Virsi-A_ikonas_-04.svg"},{"name":"G","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/5\/Virsi-A_ikonas_-06.svg"},{"name":"WC","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/7\/Virsi-A_ikonas_-07.svg"},{"name":"Veikals","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/8\/Virsi-A_ikonas_-08.svg"},{"name":"Kafija","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/9\/Virsi-A_ikonas_-09.svg"},{"name":"Uzkodas","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/10\/Virsi-A_ikonas_-10.svg"},{"name":"WiFi","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/13\/Virsi-A_ikonas_-13.svg"},{"name":"Gaiss","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/14\/Virsi-A_ikonas_-14.svg"},{"name":"\u016adens","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/16\/Virsi-A_ikonas_-16.svg"},{"name":"Piekabju noma","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/17\/Virsi-A_ikonas_-17.svg"},{"name":"Cash","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/18\/Virsi-A_ikonas_-18.svg"}]","data-lng":"27.25788","data-lat":"57.1386538","children":[
                  {"tag":"span","class":"title","html":"DUS "Balvi""}
                ]}
            ]},
          {"tag":"li","class":"dus__list__item dus__list__item--19","children":[
              {"tag":"a","class":"map-link","id":"dus_6","href":"http://www.virsia.lv/lv/uzpildes-stacijas/#dus/6","data-contacts":""Dīķmalas", Bebru pagasts, Kokneses novads, LV-5135<br ></a>
Tālr.: +371 65164595<br />
Darba laiks: 06:00 - 23:00<br />
<br />
","data-fuels":"[{"name":"95E","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/1\/Virsi-A_ikonas_-01.svg"},{"name":"DD","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/3\/Virsi-A_ikonas_-03.svg"},{"name":"AD","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/4\/Virsi-A_ikonas_-04.svg"},{"name":"WC","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/7\/Virsi-A_ikonas_-07.svg"},{"name":"Veikals","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/8\/Virsi-A_ikonas_-08.svg"},{"name":"Kafija","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/9\/Virsi-A_ikonas_-09.svg"},{"name":"Uzkodas","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/10\/Virsi-A_ikonas_-10.svg"},{"name":"Gaiss","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/14\/Virsi-A_ikonas_-14.svg"},{"name":"\u016adens","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/16\/Virsi-A_ikonas_-16.svg"}]","data-lng":"25.48891960000003","data-lat":"56.7198417","children":[
                  {"tag":"span","class":"title","html":"DUS "Bebri""}
                ]}
            ]},
          {"tag":"li","class":"dus__list__item dus__list__item--1","children":[
              {"tag":"a","class":"map-link","id":"dus_47","href":"http://www.virsia.lv/lv/uzpildes-stacijas/#dus/47","data-contacts":""Cerības", Krustkalni, Ķekavas pagasts, LV-2111<br ></a>
Tālr.:+371 67808239<br />
Darba laiks: 00:00 - 24:00<br />
","data-fuels":"[{"name":"95E","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/1\/Virsi-A_ikonas_-01.svg"},{"name":"98","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/2\/Virsi-A_ikonas_-02.svg"},{"name":"DD","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/3\/Virsi-A_ikonas_-03.svg"},{"name":"AD Blue","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/6\/Virsi-A_ikonas_-05.svg"},{"name":"WC","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/7\/Virsi-A_ikonas_-07.svg"},{"name":"Veikals","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/8\/Virsi-A_ikonas_-08.svg"},{"name":"Kafija","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/9\/Virsi-A_ikonas_-09.svg"},{"name":"Uzkodas","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/10\/Virsi-A_ikonas_-10.svg"},{"name":"Auto mazg\u0101tavu","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/11\/Virsi-A_ikonas_-11.svg"},{"name":"WiFi","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/13\/Virsi-A_ikonas_-13.svg"},{"name":"Gaiss","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/14\/Virsi-A_ikonas_-14.svg"},{"name":"\u016adens","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/16\/Virsi-A_ikonas_-16.svg"},{"name":"Piekabju noma","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/17\/Virsi-A_ikonas_-17.svg"}]","data-lng":"24.148259199999984","data-lat":"56.8898561","children":[
                  {"tag":"span","class":"title","html":"DUS "Baloži""}
                ]}
            ]},
          {"tag":"li","class":"dus__list__item dus__list__item--1","children":[
              {"tag":"a","class":"map-link","id":"dus_67","href":"http://www.virsia.lv/lv/uzpildes-stacijas/#dus/67","data-contacts":"Brīvības gatve 250, Rīga, LV-1039<br ></a>
Tālr.:64292270<br />
Darba laiks: 00:00 - 24:00","data-fuels":"[{"name":"95E","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/1\/Virsi-A_ikonas_-01.svg"},{"name":"98","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/2\/Virsi-A_ikonas_-02.svg"},{"name":"DD","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/3\/Virsi-A_ikonas_-03.svg"},{"name":"WC","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/7\/Virsi-A_ikonas_-07.svg"},{"name":"Veikals","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/8\/Virsi-A_ikonas_-08.svg"},{"name":"Kafija","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/9\/Virsi-A_ikonas_-09.svg"},{"name":"Uzkodas","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/10\/Virsi-A_ikonas_-10.svg"},{"name":"Auto mazg\u0101tavu","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/11\/Virsi-A_ikonas_-11.svg"},{"name":"WiFi","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/13\/Virsi-A_ikonas_-13.svg"},{"name":"Gaiss","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/14\/Virsi-A_ikonas_-14.svg"},{"name":"\u016adens","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/16\/Virsi-A_ikonas_-16.svg"}]","data-lng":"24.173369644207696","data-lat":"56.97518330353912","children":[
                  {"tag":"span","class":"title","html":"DUS "Brīvība""}
                ]}
            ]},
          {"tag":"li","class":"dus__list__item dus__list__item--10","children":[
              {"tag":"a","class":"map-link","id":"dus_7","href":"http://www.virsia.lv/lv/uzpildes-stacijas/#dus/7","data-contacts":"Raiņa iela 32, Cēsis, LV-4101<br ></a>
Tālr.:+ 371 64121933<br />
Darba laiks: 00:00 - 24:00<br />
","data-fuels":"[{"name":"95E","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/1\/Virsi-A_ikonas_-01.svg"},{"name":"98","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/2\/Virsi-A_ikonas_-02.svg"},{"name":"DD","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/3\/Virsi-A_ikonas_-03.svg"},{"name":"WC","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/7\/Virsi-A_ikonas_-07.svg"},{"name":"Veikals","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/8\/Virsi-A_ikonas_-08.svg"},{"name":"Kafija","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/9\/Virsi-A_ikonas_-09.svg"},{"name":"Uzkodas","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/10\/Virsi-A_ikonas_-10.svg"},{"name":"WiFi","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/13\/Virsi-A_ikonas_-13.svg"},{"name":"Gaiss","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/14\/Virsi-A_ikonas_-14.svg"},{"name":"\u016adens","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/16\/Virsi-A_ikonas_-16.svg"},{"name":"Piekabju noma","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/17\/Virsi-A_ikonas_-17.svg"}]","data-lng":"25.280136099999936","data-lat":"57.31197100000001","children":[
                  {"tag":"span","class":"title","html":"DUS "Cēsis""}
                ]}
            ]},
          {"tag":"li","class":"dus__list__item dus__list__item--10","children":[
              {"tag":"a","class":"map-link","id":"dus_60","href":"http://www.virsia.lv/lv/uzpildes-stacijas/#dus/60","data-contacts":""Piebalgas 99A", Vaives pagsts, Cēsu novads, LV-4136<br ></a>
Tālr.:+371 64100815<br />
Darba laiks: 00:00 - 24:00<br />
","data-fuels":"[{"name":"95E","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/1\/Virsi-A_ikonas_-01.svg"},{"name":"DD","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/3\/Virsi-A_ikonas_-03.svg"},{"name":"AD","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/4\/Virsi-A_ikonas_-04.svg"},{"name":"G","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/5\/Virsi-A_ikonas_-06.svg"},{"name":"WC","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/7\/Virsi-A_ikonas_-07.svg"},{"name":"Veikals","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/8\/Virsi-A_ikonas_-08.svg"},{"name":"Kafija","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/9\/Virsi-A_ikonas_-09.svg"},{"name":"Uzkodas","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/10\/Virsi-A_ikonas_-10.svg"},{"name":"WiFi","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/13\/Virsi-A_ikonas_-13.svg"},{"name":"Gaiss","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/14\/Virsi-A_ikonas_-14.svg"},{"name":"\u016adens","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/16\/Virsi-A_ikonas_-16.svg"},{"name":"Piekabju noma","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/17\/Virsi-A_ikonas_-17.svg"}]","data-lng":"25.306281300000023","data-lat":"57.29632400000001","children":[
                  {"tag":"span","class":"title","html":"DUS "Cēsis Saulrīti""}
                ]}
            ]},
          {"tag":"li","class":"dus__list__item dus__list__item--1","children":[
              {"tag":"a","class":"map-link","id":"dus_61","href":"http://www.virsia.lv/lv/uzpildes-stacijas/#dus/61","data-contacts":"Daugavgrīvas iela 136a, Rīga, LV-1055<br ></a>
Tālr.: +371 67472946<br />
Darba laiks: 00:00 - 24:00","data-fuels":"[{"name":"95E","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/1\/Virsi-A_ikonas_-01.svg"},{"name":"98","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/2\/Virsi-A_ikonas_-02.svg"},{"name":"DD","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/3\/Virsi-A_ikonas_-03.svg"},{"name":"AD Blue","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/6\/Virsi-A_ikonas_-05.svg"},{"name":"WC","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/7\/Virsi-A_ikonas_-07.svg"},{"name":"Veikals","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/8\/Virsi-A_ikonas_-08.svg"},{"name":"Kafija","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/9\/Virsi-A_ikonas_-09.svg"},{"name":"Uzkodas","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/10\/Virsi-A_ikonas_-10.svg"},{"name":"Auto mazg\u0101tavu","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/11\/Virsi-A_ikonas_-11.svg"},{"name":"WiFi","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/13\/Virsi-A_ikonas_-13.svg"},{"name":"Gaiss","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/14\/Virsi-A_ikonas_-14.svg"},{"name":"\u016adens","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/16\/Virsi-A_ikonas_-16.svg"},{"name":"Piekabju noma","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/17\/Virsi-A_ikonas_-17.svg"}]","data-lng":"24.07323304655756","data-lat":"56.974921756381946","children":[
                  {"tag":"span","class":"title","html":"DUS "Daugavgrīva""}
                ]}
            ]},
          {"tag":"li","class":"dus__list__item dus__list__item--18","children":[
              {"tag":"a","class":"map-link","id":"dus_8","href":"http://www.virsia.lv/lv/uzpildes-stacijas/#dus/8","data-contacts":"Dzelmeskrasti, Jumparavas pagasts, Lielvārdes novads, LV-5022<br ></a>
Tālr.: +371 65058923<br />
Darba laiks: 00:00 - 24:00<br />
","data-fuels":"[{"name":"95E","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/1\/Virsi-A_ikonas_-01.svg"},{"name":"DD","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/3\/Virsi-A_ikonas_-03.svg"},{"name":"AD","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/4\/Virsi-A_ikonas_-04.svg"},{"name":"WC","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/7\/Virsi-A_ikonas_-07.svg"},{"name":"Veikals","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/8\/Virsi-A_ikonas_-08.svg"},{"name":"Kafija","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/9\/Virsi-A_ikonas_-09.svg"},{"name":"Uzkodas","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/10\/Virsi-A_ikonas_-10.svg"},{"name":"WiFi","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/13\/Virsi-A_ikonas_-13.svg"},{"name":"Gaiss","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/14\/Virsi-A_ikonas_-14.svg"},{"name":"\u016adens","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/16\/Virsi-A_ikonas_-16.svg"},{"name":"Piekabju noma","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/17\/Virsi-A_ikonas_-17.svg"}]","data-lng":"24.91498869999998","data-lat":"56.6422539","children":[
                  {"tag":"span","class":"title","html":"DUS "Dzelmes""}
                ]}
            ]},
          {"tag":"li","class":"dus__list__item dus__list__item--8","children":[
              {"tag":"a","class":"map-link","id":"dus_55","href":"http://www.virsia.lv/lv/uzpildes-stacijas/#dus/55","data-contacts":"Dārza iela 7, Ēdole, Ēdoles pagasts, Kuldīgas novads, LV-3310<br ></a>
Tālr.: +371 63345303<br />
Darba laiks: 06:00 - 23:00","data-fuels":"[{"name":"95E","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/1\/Virsi-A_ikonas_-01.svg"},{"name":"DD","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/3\/Virsi-A_ikonas_-03.svg"},{"name":"AD","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/4\/Virsi-A_ikonas_-04.svg"},{"name":"WC","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/7\/Virsi-A_ikonas_-07.svg"},{"name":"Veikals","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/8\/Virsi-A_ikonas_-08.svg"},{"name":"Kafija","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/9\/Virsi-A_ikonas_-09.svg"},{"name":"Uzkodas","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/10\/Virsi-A_ikonas_-10.svg"},{"name":"Gaiss","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/14\/Virsi-A_ikonas_-14.svg"},{"name":"\u016adens","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/16\/Virsi-A_ikonas_-16.svg"}]","data-lng":"21.690887799999928","data-lat":"57.0213021","children":[
                  {"tag":"span","class":"title","html":"DUS "Ēdole""}
                ]}
            ]},
          {"tag":"li","class":"dus__list__item dus__list__item--21","children":[
              {"tag":"a","class":"map-link","id":"dus_9","href":"http://www.virsia.lv/lv/uzpildes-stacijas/#dus/9","data-contacts":"Gaismas iela 1, Aizkraukle, LV-5101<br ></a>
Tālr.: +371 65122376<br />
Darba laiks: 00:00 - 24:00","data-fuels":"[{"name":"95E","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/1\/Virsi-A_ikonas_-01.svg"},{"name":"98","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/2\/Virsi-A_ikonas_-02.svg"},{"name":"DD","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/3\/Virsi-A_ikonas_-03.svg"},{"name":"WC","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/7\/Virsi-A_ikonas_-07.svg"},{"name":"Veikals","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/8\/Virsi-A_ikonas_-08.svg"},{"name":"Kafija","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/9\/Virsi-A_ikonas_-09.svg"},{"name":"Uzkodas","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/10\/Virsi-A_ikonas_-10.svg"},{"name":"WiFi","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/13\/Virsi-A_ikonas_-13.svg"},{"name":"Gaiss","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/14\/Virsi-A_ikonas_-14.svg"},{"name":"\u016adens","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/16\/Virsi-A_ikonas_-16.svg"}]","data-lng":"25.24461450000001","data-lat":"56.5985082","children":[
                  {"tag":"span","class":"title","html":"DUS "Gaisma""}
                ]}
            ]},
          {"tag":"li","class":"dus__list__item dus__list__item--1","children":[
              {"tag":"a","class":"map-link","id":"dus_48","href":"http://www.virsia.lv/lv/uzpildes-stacijas/#dus/48","data-contacts":"Granīta iela 13a, Rumbula, Stopiņu novads, LV-2130<br ></a>
Tālr.: +371 67254456<br />
Darba laiks: 00:00 - 24:00<br />
","data-fuels":"[{"name":"95E","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/1\/Virsi-A_ikonas_-01.svg"},{"name":"DD","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/3\/Virsi-A_ikonas_-03.svg"},{"name":"G","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/5\/Virsi-A_ikonas_-06.svg"},{"name":"AD Blue","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/6\/Virsi-A_ikonas_-05.svg"},{"name":"WC","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/7\/Virsi-A_ikonas_-07.svg"},{"name":"Veikals","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/8\/Virsi-A_ikonas_-08.svg"},{"name":"Kafija","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/9\/Virsi-A_ikonas_-09.svg"},{"name":"Uzkodas","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/10\/Virsi-A_ikonas_-10.svg"},{"name":"WiFi","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/13\/Virsi-A_ikonas_-13.svg"},{"name":"Gaiss","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/14\/Virsi-A_ikonas_-14.svg"}]","data-lng":"24.23780173068849","data-lat":"56.91330529999713","children":[
                  {"tag":"span","class":"title","html":"DUS "Granīta""}
                ]}
            ]},
          {"tag":"li","class":"dus__list__item dus__list__item--51","children":[
              {"tag":"a","class":"map-link","id":"dus_10","href":"http://www.virsia.lv/lv/uzpildes-stacijas/#dus/10","data-contacts":"Brīvības iela 97b, Gulbene, LV-4401<br ></a>
Tālr.: +371 64472150<br />
Darba laiks: 00:00 - 24:00","data-fuels":"[{"name":"95E","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/1\/Virsi-A_ikonas_-01.svg"},{"name":"98","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/2\/Virsi-A_ikonas_-02.svg"},{"name":"DD","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/3\/Virsi-A_ikonas_-03.svg"},{"name":"AD","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/4\/Virsi-A_ikonas_-04.svg"},{"name":"AD Blue","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/6\/Virsi-A_ikonas_-05.svg"},{"name":"WC","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/7\/Virsi-A_ikonas_-07.svg"},{"name":"Veikals","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/8\/Virsi-A_ikonas_-08.svg"},{"name":"Kafija","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/9\/Virsi-A_ikonas_-09.svg"},{"name":"Uzkodas","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/10\/Virsi-A_ikonas_-10.svg"},{"name":"WiFi","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/13\/Virsi-A_ikonas_-13.svg"},{"name":"Gaiss","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/14\/Virsi-A_ikonas_-14.svg"},{"name":"\u016adens","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/16\/Virsi-A_ikonas_-16.svg"}]","data-lng":"26.737359903149354","data-lat":"57.18272456174953","children":[
                  {"tag":"span","class":"title","html":"DUS "Gulbene""}
                ]}
            ]},
          {"tag":"li","class":"dus__list__item dus__list__item--48","children":[
              {"tag":"a","class":"map-link","id":"dus_64","href":"http://www.virsia.lv/lv/uzpildes-stacijas/#dus/64","data-contacts":"DUS Grenctāle, Brunavas pag., <br ></a>
Bauskas novads, LV-3907<br />
Tālr.: + 371 63946922<br />
Darba laiks: 00:00 - 24:00","data-fuels":"[{"name":"95E","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/1\/Virsi-A_ikonas_-01.svg"},{"name":"DD","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/3\/Virsi-A_ikonas_-03.svg"},{"name":"G","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/5\/Virsi-A_ikonas_-06.svg"},{"name":"AD Blue","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/6\/Virsi-A_ikonas_-05.svg"},{"name":"WC","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/7\/Virsi-A_ikonas_-07.svg"},{"name":"Veikals","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/8\/Virsi-A_ikonas_-08.svg"},{"name":"Kafija","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/9\/Virsi-A_ikonas_-09.svg"},{"name":"Uzkodas","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/10\/Virsi-A_ikonas_-10.svg"},{"name":"Pay with cards","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/12\/Virsi-A_ikonas_-12.svg"},{"name":"WiFi","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/13\/Virsi-A_ikonas_-13.svg"},{"name":"Gaiss","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/14\/Virsi-A_ikonas_-14.svg"},{"name":"\u016adens","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/16\/Virsi-A_ikonas_-16.svg"},{"name":"Cash","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/18\/Virsi-A_ikonas_-18.svg"}]","data-lng":"24.33128521154788","data-lat":"56.31454551681341","children":[
                  {"tag":"span","class":"title","html":"DUS "Grenctāle""}
                ]}
            ]},
          {"tag":"li","class":"dus__list__item dus__list__item--23","children":[
              {"tag":"a","class":"map-link","id":"dus_34","href":"http://www.virsia.lv/lv/uzpildes-stacijas/#dus/34","data-contacts":""Stropica", Naujenes pagasts, Daugavpils novads, LV-5304<br ></a>
Tālr.: +371 65438054<br />
Darba laiks: 00:00 - 24:00<br />
","data-fuels":"[{"name":"95E","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/1\/Virsi-A_ikonas_-01.svg"},{"name":"DD","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/3\/Virsi-A_ikonas_-03.svg"},{"name":"AD","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/4\/Virsi-A_ikonas_-04.svg"},{"name":"AD Blue","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/6\/Virsi-A_ikonas_-05.svg"},{"name":"WC","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/7\/Virsi-A_ikonas_-07.svg"},{"name":"Veikals","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/8\/Virsi-A_ikonas_-08.svg"},{"name":"Kafija","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/9\/Virsi-A_ikonas_-09.svg"},{"name":"Uzkodas","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/10\/Virsi-A_ikonas_-10.svg"},{"name":"WiFi","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/13\/Virsi-A_ikonas_-13.svg"},{"name":"Gaiss","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/14\/Virsi-A_ikonas_-14.svg"},{"name":"\u016adens","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/16\/Virsi-A_ikonas_-16.svg"}]","data-lng":"26.636451999999963","data-lat":"55.9299936","children":[
                  {"tag":"span","class":"title","html":"DUS "Ilgas""}
                ]}
            ]},
          {"tag":"li","class":"dus__list__item dus__list__item--24","children":[
              {"tag":"a","class":"map-link","id":"dus_12","href":"http://www.virsia.lv/lv/uzpildes-stacijas/#dus/12","data-contacts":"J. Akurātera iela 13, Jēkabpils, LV-5201<br ></a>
Tālr.:+371 65235483<br />
Darba laiks: 06:00 - 23:00<br />
","data-fuels":"[{"name":"95E","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/1\/Virsi-A_ikonas_-01.svg"},{"name":"98","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/2\/Virsi-A_ikonas_-02.svg"},{"name":"DD","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/3\/Virsi-A_ikonas_-03.svg"},{"name":"AD","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/4\/Virsi-A_ikonas_-04.svg"},{"name":"WC","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/7\/Virsi-A_ikonas_-07.svg"},{"name":"Veikals","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/8\/Virsi-A_ikonas_-08.svg"},{"name":"Kafija","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/9\/Virsi-A_ikonas_-09.svg"},{"name":"Uzkodas","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/10\/Virsi-A_ikonas_-10.svg"},{"name":"WiFi","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/13\/Virsi-A_ikonas_-13.svg"},{"name":"Gaiss","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/14\/Virsi-A_ikonas_-14.svg"},{"name":"\u016adens","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/16\/Virsi-A_ikonas_-16.svg"},{"name":"Cash","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/18\/Virsi-A_ikonas_-18.svg"}]","data-lng":"25.880065400000035","data-lat":"56.4861276","children":[
                  {"tag":"span","class":"title","html":"DUS "Jēkabpils""}
                ]}
            ]},
          {"tag":"li","class":"dus__list__item dus__list__item--1","children":[
              {"tag":"a","class":"map-link","id":"dus_49","href":"http://www.virsia.lv/lv/uzpildes-stacijas/#dus/49","data-contacts":""Prauliņi", Amatnieki, Garkalnes novads, LV-2137<br ></a>
Tālr.: +371 67348947<br />
Darba laiks: 00:00 - 24:00<br />
","data-fuels":"[{"name":"95E","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/1\/Virsi-A_ikonas_-01.svg"},{"name":"98","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/2\/Virsi-A_ikonas_-02.svg"},{"name":"DD","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/3\/Virsi-A_ikonas_-03.svg"},{"name":"G","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/5\/Virsi-A_ikonas_-06.svg"},{"name":"WC","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/7\/Virsi-A_ikonas_-07.svg"},{"name":"Veikals","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/8\/Virsi-A_ikonas_-08.svg"},{"name":"Kafija","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/9\/Virsi-A_ikonas_-09.svg"},{"name":"Uzkodas","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/10\/Virsi-A_ikonas_-10.svg"},{"name":"WiFi","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/13\/Virsi-A_ikonas_-13.svg"},{"name":"Gaiss","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/14\/Virsi-A_ikonas_-14.svg"},{"name":"\u016adens","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/16\/Virsi-A_ikonas_-16.svg"},{"name":"Piekabju noma","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/17\/Virsi-A_ikonas_-17.svg"}]","data-lng":"24.340424100000064","data-lat":"56.9703508","children":[
                  {"tag":"span","class":"title","html":"DUS "Jugla""}
                ]}
            ]},
          {"tag":"li","class":"dus__list__item dus__list__item--9","children":[
              {"tag":"a","class":"map-link","id":"dus_56","href":"http://www.virsia.lv/lv/uzpildes-stacijas/#dus/56","data-contacts":""Krastnieki", Jūrkalne, Jūrkalnes pagasts, Ventspils novads, LV-3626<br ></a>
Tālr.:+371 63630084<br />
Darba laiks: 06:00 - 23:00","data-fuels":"[{"name":"95E","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/1\/Virsi-A_ikonas_-01.svg"},{"name":"DD","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/3\/Virsi-A_ikonas_-03.svg"},{"name":"AD","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/4\/Virsi-A_ikonas_-04.svg"},{"name":"WC","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/7\/Virsi-A_ikonas_-07.svg"},{"name":"Veikals","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/8\/Virsi-A_ikonas_-08.svg"},{"name":"Kafija","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/9\/Virsi-A_ikonas_-09.svg"},{"name":"Uzkodas","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/10\/Virsi-A_ikonas_-10.svg"},{"name":"Gaiss","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/14\/Virsi-A_ikonas_-14.svg"},{"name":"\u016adens","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/16\/Virsi-A_ikonas_-16.svg"}]","data-lng":"21.391514400000005","data-lat":"57.0119262","children":[
                  {"tag":"span","class":"title","html":"DUS "Jūrkalne""}
                ]}
            ]},
          {"tag":"li","class":"dus__list__item dus__list__item--26","children":[
              {"tag":"a","class":"map-link","id":"dus_29","href":"http://www.virsia.lv/lv/uzpildes-stacijas/#dus/29","data-contacts":"Abavas iela 4, Kandava, LV-3120<br ></a>
Tāl.: +371 63126589<br />
Darba laiks: 00:00 - 24:00<br />
","data-fuels":"[{"name":"95E","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/1\/Virsi-A_ikonas_-01.svg"},{"name":"98","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/2\/Virsi-A_ikonas_-02.svg"},{"name":"DD","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/3\/Virsi-A_ikonas_-03.svg"},{"name":"AD","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/4\/Virsi-A_ikonas_-04.svg"},{"name":"WC","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/7\/Virsi-A_ikonas_-07.svg"},{"name":"Veikals","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/8\/Virsi-A_ikonas_-08.svg"},{"name":"Kafija","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/9\/Virsi-A_ikonas_-09.svg"},{"name":"Uzkodas","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/10\/Virsi-A_ikonas_-10.svg"},{"name":"Auto mazg\u0101tavu","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/11\/Virsi-A_ikonas_-11.svg"},{"name":"Gaiss","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/14\/Virsi-A_ikonas_-14.svg"},{"name":"\u016adens","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/16\/Virsi-A_ikonas_-16.svg"},{"name":"Piekabju noma","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/17\/Virsi-A_ikonas_-17.svg"}]","data-lng":"22.781189700000027","data-lat":"57.0351699","children":[
                  {"tag":"span","class":"title","html":"DUS "Kandava""}
                ]}
            ]},
          {"tag":"li","class":"dus__list__item dus__list__item--27","children":[
              {"tag":"a","class":"map-link","id":"dus_35","href":"http://www.virsia.lv/lv/uzpildes-stacijas/#dus/35","data-contacts":""Passim", Malnavas pagasts, Kārsavas novads, LV-5717<br ></a>
Tālr.: +371 65781130<br />
Darba laiks: 00:00 - 24:00<br />
","data-fuels":"[{"name":"95E","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/1\/Virsi-A_ikonas_-01.svg"},{"name":"DD","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/3\/Virsi-A_ikonas_-03.svg"},{"name":"AD","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/4\/Virsi-A_ikonas_-04.svg"},{"name":"G","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/5\/Virsi-A_ikonas_-06.svg"},{"name":"WC","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/7\/Virsi-A_ikonas_-07.svg"},{"name":"Veikals","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/8\/Virsi-A_ikonas_-08.svg"},{"name":"Kafija","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/9\/Virsi-A_ikonas_-09.svg"},{"name":"Uzkodas","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/10\/Virsi-A_ikonas_-10.svg"},{"name":"WiFi","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/13\/Virsi-A_ikonas_-13.svg"},{"name":"Gaiss","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/14\/Virsi-A_ikonas_-14.svg"},{"name":"\u016adens","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/16\/Virsi-A_ikonas_-16.svg"}]","data-lng":"27.696934800000008","data-lat":"56.7808028","children":[
                  {"tag":"span","class":"title","html":"DUS "Kārsava""}
                ]}
            ]},
          {"tag":"li","class":"dus__list__item dus__list__item--28","children":[
              {"tag":"a","class":"map-link","id":"dus_13","href":"http://www.virsia.lv/lv/uzpildes-stacijas/#dus/13","data-contacts":"Melioratoru iela 1M, Koknese, LV-5113<br ></a>
Tālr.:+371 29129696<br />
Darba laiks: 00:00 - 24:00","data-fuels":"[{"name":"95E","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/1\/Virsi-A_ikonas_-01.svg"},{"name":"DD","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/3\/Virsi-A_ikonas_-03.svg"},{"name":"Pay with cards","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/12\/Virsi-A_ikonas_-12.svg"}]","data-lng":"25.442896399999995","data-lat":"56.64504660000001","children":[
                  {"tag":"span","class":"title","html":"ADUS "Koknese" "}
                ]}
            ]},
          {"tag":"li","class":"dus__list__item dus__list__item--29","children":[
              {"tag":"a","class":"map-link","id":"dus_36","href":"http://www.virsia.lv/lv/uzpildes-stacijas/#dus/36","data-contacts":"Zīlānu iela 145, Kūku pagasts, Krustpils novads, LV-5222<br ></a>
Tālr.: +371 65230081<br />
Darba laiks: 00:00 - 24:00<br />
","data-fuels":"[{"name":"95E","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/1\/Virsi-A_ikonas_-01.svg"},{"name":"98","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/2\/Virsi-A_ikonas_-02.svg"},{"name":"DD","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/3\/Virsi-A_ikonas_-03.svg"},{"name":"AD","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/4\/Virsi-A_ikonas_-04.svg"},{"name":"AD Blue","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/6\/Virsi-A_ikonas_-05.svg"},{"name":"WC","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/7\/Virsi-A_ikonas_-07.svg"},{"name":"Veikals","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/8\/Virsi-A_ikonas_-08.svg"},{"name":"Kafija","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/9\/Virsi-A_ikonas_-09.svg"},{"name":"Uzkodas","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/10\/Virsi-A_ikonas_-10.svg"},{"name":"WiFi","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/13\/Virsi-A_ikonas_-13.svg"},{"name":"Gaiss","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/14\/Virsi-A_ikonas_-14.svg"},{"name":"\u016adens","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/16\/Virsi-A_ikonas_-16.svg"}]","data-lng":"25.930580400000053","data-lat":"56.512524","children":[
                  {"tag":"span","class":"title","html":"DUS "Krustpils""}
                ]}
            ]},
          {"tag":"li","class":"dus__list__item dus__list__item--6","children":[
              {"tag":"a","class":"map-link","id":"dus_68","href":"http://www.virsia.lv/lv/uzpildes-stacijas/#dus/68","data-contacts":"Zemnieku iela 24, Liepāja, LV-3401<br ></a>
Tālr.: +371 63451440<br />
Darba laiks: 00:00 - 24:00","data-fuels":"[{"name":"95E","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/1\/Virsi-A_ikonas_-01.svg"},{"name":"98","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/2\/Virsi-A_ikonas_-02.svg"},{"name":"DD","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/3\/Virsi-A_ikonas_-03.svg"},{"name":"AD","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/4\/Virsi-A_ikonas_-04.svg"},{"name":"G","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/5\/Virsi-A_ikonas_-06.svg"},{"name":"AD Blue","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/6\/Virsi-A_ikonas_-05.svg"},{"name":"WC","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/7\/Virsi-A_ikonas_-07.svg"},{"name":"Veikals","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/8\/Virsi-A_ikonas_-08.svg"},{"name":"Kafija","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/9\/Virsi-A_ikonas_-09.svg"},{"name":"Uzkodas","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/10\/Virsi-A_ikonas_-10.svg"},{"name":"Pay with cards","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/12\/Virsi-A_ikonas_-12.svg"},{"name":"WiFi","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/13\/Virsi-A_ikonas_-13.svg"},{"name":"Gaiss","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/14\/Virsi-A_ikonas_-14.svg"},{"name":"\u016adens","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/16\/Virsi-A_ikonas_-16.svg"},{"name":"Cash","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/18\/Virsi-A_ikonas_-18.svg"}]","data-lng":"21.021245300000032","data-lat":"56.5173026","children":[
                  {"tag":"span","class":"title","html":"DUS "Liepāja""}
                ]}
            ]},
          {"tag":"li","class":"dus__list__item dus__list__item--31","children":[
              {"tag":"a","class":"map-link","id":"dus_15","href":"http://www.virsia.lv/lv/uzpildes-stacijas/#dus/15","data-contacts":""Ceļmalas", Liezēres pagasts, Madonas novads, LV-4884<br ></a>
Tālr.: +371 64821316<br />
Darba laiks: 06:00 - 23:00<br />
","data-fuels":"[{"name":"95E","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/1\/Virsi-A_ikonas_-01.svg"},{"name":"DD","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/3\/Virsi-A_ikonas_-03.svg"},{"name":"AD","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/4\/Virsi-A_ikonas_-04.svg"},{"name":"WC","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/7\/Virsi-A_ikonas_-07.svg"},{"name":"Veikals","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/8\/Virsi-A_ikonas_-08.svg"},{"name":"Kafija","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/9\/Virsi-A_ikonas_-09.svg"},{"name":"Uzkodas","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/10\/Virsi-A_ikonas_-10.svg"},{"name":"WiFi","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/13\/Virsi-A_ikonas_-13.svg"},{"name":"\u016adens","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/16\/Virsi-A_ikonas_-16.svg"}]","data-lng":"26.044616058227575","data-lat":"56.973387184049336","children":[
                  {"tag":"span","class":"title","html":"DUS "Liezēre""}
                ]}
            ]},
          {"tag":"li","class":"dus__list__item dus__list__item--32","children":[
              {"tag":"a","class":"map-link","id":"dus_37","href":"http://www.virsia.lv/lv/uzpildes-stacijas/#dus/37","data-contacts":""Bērziņi-s",Cirmas pagasts, Ludzas novads, LV-5735<br ></a>
Tālr.: +371 65707149<br />
Darba laiks: 00:00 - 24:00<br />
","data-fuels":"[{"name":"95E","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/1\/Virsi-A_ikonas_-01.svg"},{"name":"98","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/2\/Virsi-A_ikonas_-02.svg"},{"name":"DD","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/3\/Virsi-A_ikonas_-03.svg"},{"name":"AD","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/4\/Virsi-A_ikonas_-04.svg"},{"name":"G","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/5\/Virsi-A_ikonas_-06.svg"},{"name":"WC","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/7\/Virsi-A_ikonas_-07.svg"},{"name":"Veikals","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/8\/Virsi-A_ikonas_-08.svg"},{"name":"Kafija","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/9\/Virsi-A_ikonas_-09.svg"},{"name":"Uzkodas","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/10\/Virsi-A_ikonas_-10.svg"},{"name":"Gaiss","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/14\/Virsi-A_ikonas_-14.svg"},{"name":"\u016adens","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/16\/Virsi-A_ikonas_-16.svg"},{"name":"Cash","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/18\/Virsi-A_ikonas_-18.svg"}]","data-lng":"27.681988000000047","data-lat":"56.536348","children":[
                  {"tag":"span","class":"title","html":"DUS "Ludza""}
                ]}
            ]},
          {"tag":"li","class":"dus__list__item dus__list__item--33","children":[
              {"tag":"a","class":"map-link","id":"dus_16","href":"http://www.virsia.lv/lv/uzpildes-stacijas/#dus/16","data-contacts":"Rūpniecības iela 49a, Madona, LV-4801<br ></a>
Tālr.:+371 64860622, +371 64860623<br />
Darba laiks: 06:00 - 23:00<br />
","data-fuels":"[{"name":"95E","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/1\/Virsi-A_ikonas_-01.svg"},{"name":"98","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/2\/Virsi-A_ikonas_-02.svg"},{"name":"DD","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/3\/Virsi-A_ikonas_-03.svg"},{"name":"AD","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/4\/Virsi-A_ikonas_-04.svg"},{"name":"WC","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/7\/Virsi-A_ikonas_-07.svg"},{"name":"Veikals","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/8\/Virsi-A_ikonas_-08.svg"},{"name":"Kafija","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/9\/Virsi-A_ikonas_-09.svg"},{"name":"Uzkodas","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/10\/Virsi-A_ikonas_-10.svg"},{"name":"WiFi","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/13\/Virsi-A_ikonas_-13.svg"},{"name":"Gaiss","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/14\/Virsi-A_ikonas_-14.svg"},{"name":"\u016adens","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/16\/Virsi-A_ikonas_-16.svg"},{"name":"Cash","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/18\/Virsi-A_ikonas_-18.svg"}]","data-lng":"26.231084399999986","data-lat":"56.8598671","children":[
                  {"tag":"span","class":"title","html":"DUS "Madona""}
                ]}
            ]},
          {"tag":"li","class":"dus__list__item dus__list__item--34","children":[
              {"tag":"a","class":"map-link","id":"dus_17","href":"http://www.virsia.lv/lv/uzpildes-stacijas/#dus/17","data-contacts":"Skulmes iela 5, Mālpils, Mālpils nov., LV-2152<br ></a>
Tālr.: +371 67925496<br />
Darba laiks: 06:00 - 23:00<br />
","data-fuels":"[{"name":"95E","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/1\/Virsi-A_ikonas_-01.svg"},{"name":"98","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/2\/Virsi-A_ikonas_-02.svg"},{"name":"DD","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/3\/Virsi-A_ikonas_-03.svg"},{"name":"AD","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/4\/Virsi-A_ikonas_-04.svg"},{"name":"G","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/5\/Virsi-A_ikonas_-06.svg"},{"name":"WC","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/7\/Virsi-A_ikonas_-07.svg"},{"name":"Veikals","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/8\/Virsi-A_ikonas_-08.svg"},{"name":"Kafija","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/9\/Virsi-A_ikonas_-09.svg"},{"name":"Uzkodas","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/10\/Virsi-A_ikonas_-10.svg"},{"name":"WiFi","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/13\/Virsi-A_ikonas_-13.svg"},{"name":"Gaiss","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/14\/Virsi-A_ikonas_-14.svg"},{"name":"\u016adens","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/16\/Virsi-A_ikonas_-16.svg"},{"name":"Piekabju noma","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/17\/Virsi-A_ikonas_-17.svg"},{"name":"Cash","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/18\/Virsi-A_ikonas_-18.svg"}]","data-lng":"24.96537669999998","data-lat":"57.0123684","children":[
                  {"tag":"span","class":"title","html":"DUS "Mālpils""}
                ]}
            ]},
          {"tag":"li","class":"dus__list__item dus__list__item--1","children":[
              {"tag":"a","class":"map-link","id":"dus_1","href":"http://www.virsia.lv/lv/uzpildes-stacijas/#dus/1","data-contacts":"Mūkusalas iela 75b, Rīga, LV-1054<br ></a>
Darba laiks: 00:00 - 24:00","data-fuels":"[{"name":"DD","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/3\/Virsi-A_ikonas_-03.svg"}]","data-lng":"24.108303699999965","data-lat":"56.9218868","children":[
                  {"tag":"span","class":"title","html":"ADDUS "Mūkusala""}
                ]}
            ]},
          {"tag":"li","class":"dus__list__item dus__list__item--1","children":[
              {"tag":"a","class":"map-link","id":"dus_66","href":"http://www.virsia.lv/lv/uzpildes-stacijas/#dus/66","data-contacts":""Ikri", Mārupes novads, LV-2167<br ></a>
Tālr.: + 371 66902112<br />
Darba laiks: 00:00 - 24:00","data-fuels":"[{"name":"95E","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/1\/Virsi-A_ikonas_-01.svg"},{"name":"98","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/2\/Virsi-A_ikonas_-02.svg"},{"name":"DD","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/3\/Virsi-A_ikonas_-03.svg"},{"name":"G","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/5\/Virsi-A_ikonas_-06.svg"},{"name":"AD Blue","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/6\/Virsi-A_ikonas_-05.svg"},{"name":"WC","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/7\/Virsi-A_ikonas_-07.svg"},{"name":"Veikals","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/8\/Virsi-A_ikonas_-08.svg"},{"name":"Kafija","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/9\/Virsi-A_ikonas_-09.svg"},{"name":"Uzkodas","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/10\/Virsi-A_ikonas_-10.svg"},{"name":"Auto mazg\u0101tavu","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/11\/Virsi-A_ikonas_-11.svg"},{"name":"WiFi","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/13\/Virsi-A_ikonas_-13.svg"},{"name":"Gaiss","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/14\/Virsi-A_ikonas_-14.svg"},{"name":"\u016adens","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/16\/Virsi-A_ikonas_-16.svg"},{"name":"Piekabju noma","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/17\/Virsi-A_ikonas_-17.svg"}]","data-lng":"23.96207594685052","data-lat":"56.88061888057275","children":[
                  {"tag":"span","class":"title","html":"DUS "Mārupe""}
                ]}
            ]},
          {"tag":"li","class":"dus__list__item dus__list__item--1","children":[
              {"tag":"a","class":"map-link","id":"dus_51","href":"http://www.virsia.lv/lv/uzpildes-stacijas/#dus/51","data-contacts":"Pērnavas iela 78, Rīga, LV-1009<br ></a>
Tālr.: +371 67296540<br />
Darba laiks: 00:00 - 24:00<br />
","data-fuels":"[{"name":"95E","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/1\/Virsi-A_ikonas_-01.svg"},{"name":"98","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/2\/Virsi-A_ikonas_-02.svg"},{"name":"DD","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/3\/Virsi-A_ikonas_-03.svg"},{"name":"WC","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/7\/Virsi-A_ikonas_-07.svg"},{"name":"Veikals","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/8\/Virsi-A_ikonas_-08.svg"},{"name":"Kafija","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/9\/Virsi-A_ikonas_-09.svg"},{"name":"Uzkodas","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/10\/Virsi-A_ikonas_-10.svg"},{"name":"WiFi","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/13\/Virsi-A_ikonas_-13.svg"},{"name":"Gaiss","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/14\/Virsi-A_ikonas_-14.svg"},{"name":"\u016adens","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/16\/Virsi-A_ikonas_-16.svg"}]","data-lng":"24.153752742327924","data-lat":"56.950620789273145","children":[
                  {"tag":"span","class":"title","html":"DUS "Pērnava""}
                ]}
            ]},
          {"tag":"li","class":"dus__list__item dus__list__item--35","children":[
              {"tag":"a","class":"map-link","id":"dus_18","href":"http://www.virsia.lv/lv/uzpildes-stacijas/#dus/18","data-contacts":"Rīgas iela 31, Pļaviņas, LV-5120<br ></a>
Tālr.: +371 65133057<br />
Darba laiks: 06:00 - 23:00<br />
","data-fuels":"[{"name":"95E","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/1\/Virsi-A_ikonas_-01.svg"},{"name":"DD","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/3\/Virsi-A_ikonas_-03.svg"},{"name":"AD","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/4\/Virsi-A_ikonas_-04.svg"},{"name":"WC","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/7\/Virsi-A_ikonas_-07.svg"},{"name":"Veikals","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/8\/Virsi-A_ikonas_-08.svg"},{"name":"Kafija","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/9\/Virsi-A_ikonas_-09.svg"},{"name":"Uzkodas","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/10\/Virsi-A_ikonas_-10.svg"},{"name":"Gaiss","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/14\/Virsi-A_ikonas_-14.svg"},{"name":"\u016adens","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/16\/Virsi-A_ikonas_-16.svg"}]","data-lng":"25.69303590000004","data-lat":"56.61064829999999","children":[
                  {"tag":"span","class":"title","html":"DUS "Pļaviņas""}
                ]}
            ]},
          {"tag":"li","class":"dus__list__item dus__list__item--37","children":[
              {"tag":"a","class":"map-link","id":"dus_30","href":"http://www.virsia.lv/lv/uzpildes-stacijas/#dus/30","data-contacts":"Daigones iela 13a, Pūre, LV-3124<br ></a>
Tālr.: +371 63191264<br />
Darba laiks: 00:00 - 24:00<br />
","data-fuels":"[{"name":"95E","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/1\/Virsi-A_ikonas_-01.svg"},{"name":"98","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/2\/Virsi-A_ikonas_-02.svg"},{"name":"DD","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/3\/Virsi-A_ikonas_-03.svg"},{"name":"AD","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/4\/Virsi-A_ikonas_-04.svg"},{"name":"G","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/5\/Virsi-A_ikonas_-06.svg"},{"name":"WC","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/7\/Virsi-A_ikonas_-07.svg"},{"name":"Veikals","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/8\/Virsi-A_ikonas_-08.svg"},{"name":"Kafija","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/9\/Virsi-A_ikonas_-09.svg"},{"name":"Uzkodas","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/10\/Virsi-A_ikonas_-10.svg"},{"name":"WiFi","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/13\/Virsi-A_ikonas_-13.svg"},{"name":"Gaiss","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/14\/Virsi-A_ikonas_-14.svg"},{"name":"\u016adens","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/16\/Virsi-A_ikonas_-16.svg"},{"name":"Piekabju noma","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/17\/Virsi-A_ikonas_-17.svg"}]","data-lng":"22.90615600000001","data-lat":"57.0395342","children":[
                  {"tag":"span","class":"title","html":"DUS "Pūre""}
                ]}
            ]},
          {"tag":"li","class":"dus__list__item dus__list__item--38","children":[
              {"tag":"a","class":"map-link","id":"dus_19","href":"http://www.virsia.lv/lv/uzpildes-stacijas/#dus/19","data-contacts":"Tirgus iela 4, Ragana, Krimuldas novads, LV-2144<br ></a>
Tālr.: +371 67978249<br />
Darba laiks: 00:00 - 24:00<br />
","data-fuels":"[{"name":"95E","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/1\/Virsi-A_ikonas_-01.svg"},{"name":"98","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/2\/Virsi-A_ikonas_-02.svg"},{"name":"DD","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/3\/Virsi-A_ikonas_-03.svg"},{"name":"AD","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/4\/Virsi-A_ikonas_-04.svg"},{"name":"G","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/5\/Virsi-A_ikonas_-06.svg"},{"name":"AD Blue","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/6\/Virsi-A_ikonas_-05.svg"},{"name":"WC","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/7\/Virsi-A_ikonas_-07.svg"},{"name":"Veikals","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/8\/Virsi-A_ikonas_-08.svg"},{"name":"Kafija","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/9\/Virsi-A_ikonas_-09.svg"},{"name":"Uzkodas","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/10\/Virsi-A_ikonas_-10.svg"},{"name":"WiFi","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/13\/Virsi-A_ikonas_-13.svg"},{"name":"Gaiss","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/14\/Virsi-A_ikonas_-14.svg"},{"name":"\u016adens","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/16\/Virsi-A_ikonas_-16.svg"},{"name":"Piekabju noma","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/17\/Virsi-A_ikonas_-17.svg"}]","data-lng":"24.71566089999999","data-lat":"57.18007619999999","children":[
                  {"tag":"span","class":"title","html":"DUS "Ragana""}
                ]}
            ]},
          {"tag":"li","class":"dus__list__item dus__list__item--39","children":[
              {"tag":"a","class":"map-link","id":"dus_38","href":"http://www.virsia.lv/lv/uzpildes-stacijas/#dus/38","data-contacts":"VIRŠI-A, Rugāju pagasts, Rugāju novads, LV-4570<br ></a>
Tālr.: +371 64522312<br />
Darba laiks: 06:00 - 23:00<br />
","data-fuels":"[{"name":"95E","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/1\/Virsi-A_ikonas_-01.svg"},{"name":"DD","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/3\/Virsi-A_ikonas_-03.svg"},{"name":"AD","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/4\/Virsi-A_ikonas_-04.svg"},{"name":"WC","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/7\/Virsi-A_ikonas_-07.svg"},{"name":"Veikals","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/8\/Virsi-A_ikonas_-08.svg"},{"name":"Kafija","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/9\/Virsi-A_ikonas_-09.svg"},{"name":"WiFi","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/13\/Virsi-A_ikonas_-13.svg"},{"name":"Gaiss","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/14\/Virsi-A_ikonas_-14.svg"},{"name":"\u016adens","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/16\/Virsi-A_ikonas_-16.svg"}]","data-lng":"27.131728000000066","data-lat":"57.004375","children":[
                  {"tag":"span","class":"title","html":"DUS "Rugāji""}
                ]}
            ]},
          {"tag":"li","class":"dus__list__item dus__list__item--1","children":[
              {"tag":"a","class":"map-link","id":"dus_69","href":"http://www.virsia.lv/lv/uzpildes-stacijas/#dus/69","data-contacts":"Maskavas iela 450K, Rīga, LV-1063<br ></a>
Tālr.: +371 26400328<br />
Darba laiks: 00:00 - 24:00","data-fuels":"[{"name":"95E","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/1\/Virsi-A_ikonas_-01.svg"},{"name":"98","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/2\/Virsi-A_ikonas_-02.svg"},{"name":"DD","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/3\/Virsi-A_ikonas_-03.svg"},{"name":"AD","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/4\/Virsi-A_ikonas_-04.svg"},{"name":"G","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/5\/Virsi-A_ikonas_-06.svg"},{"name":"AD Blue","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/6\/Virsi-A_ikonas_-05.svg"},{"name":"WC","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/7\/Virsi-A_ikonas_-07.svg"},{"name":"Veikals","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/8\/Virsi-A_ikonas_-08.svg"},{"name":"Kafija","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/9\/Virsi-A_ikonas_-09.svg"},{"name":"Uzkodas","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/10\/Virsi-A_ikonas_-10.svg"},{"name":"Auto mazg\u0101tavu","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/11\/Virsi-A_ikonas_-11.svg"},{"name":"Pay with cards","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/12\/Virsi-A_ikonas_-12.svg"},{"name":"WiFi","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/13\/Virsi-A_ikonas_-13.svg"},{"name":"Gaiss","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/14\/Virsi-A_ikonas_-14.svg"},{"name":"\u016adens","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/16\/Virsi-A_ikonas_-16.svg"}]","data-lng":"24.242080999999985","data-lat":"56.8830336","children":[
                  {"tag":"span","class":"title","html":"DUS "Rumbula""}
                ]}
            ]},
          {"tag":"li","class":"dus__list__item dus__list__item--1","children":[
              {"tag":"a","class":"map-link","id":"dus_62","href":"http://www.virsia.lv/lv/uzpildes-stacijas/#dus/62","data-contacts":"Zviedru iela 1a, Salaspils, LV-2121<br ></a>
Tālr.: +371 67878413<br />
Darba laiks: 00:00 - 24:00","data-fuels":"[{"name":"95E","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/1\/Virsi-A_ikonas_-01.svg"},{"name":"98","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/2\/Virsi-A_ikonas_-02.svg"},{"name":"DD","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/3\/Virsi-A_ikonas_-03.svg"},{"name":"G","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/5\/Virsi-A_ikonas_-06.svg"},{"name":"AD Blue","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/6\/Virsi-A_ikonas_-05.svg"},{"name":"WC","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/7\/Virsi-A_ikonas_-07.svg"},{"name":"Veikals","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/8\/Virsi-A_ikonas_-08.svg"},{"name":"Kafija","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/9\/Virsi-A_ikonas_-09.svg"},{"name":"Uzkodas","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/10\/Virsi-A_ikonas_-10.svg"},{"name":"WiFi","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/13\/Virsi-A_ikonas_-13.svg"},{"name":"Gaiss","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/14\/Virsi-A_ikonas_-14.svg"},{"name":"\u016adens","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/16\/Virsi-A_ikonas_-16.svg"}]","data-lng":"24.326486899999963","data-lat":"56.853905","children":[
                  {"tag":"span","class":"title","html":"DUS "Salaspils""}
                ]}
            ]},
          {"tag":"li","class":"dus__list__item dus__list__item--1","children":[
              {"tag":"a","class":"map-link","id":"dus_65","href":"http://www.virsia.lv/lv/uzpildes-stacijas/#dus/65","data-contacts":"Tvaika iela 3, Rīga, LV-1005<br ></a>
Tālr.: +371 29129155<br />
Darba laiks: 06:00 - 23:00","data-fuels":"[{"name":"95E","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/1\/Virsi-A_ikonas_-01.svg"},{"name":"98","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/2\/Virsi-A_ikonas_-02.svg"},{"name":"DD","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/3\/Virsi-A_ikonas_-03.svg"},{"name":"WC","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/7\/Virsi-A_ikonas_-07.svg"},{"name":"Veikals","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/8\/Virsi-A_ikonas_-08.svg"},{"name":"Kafija","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/9\/Virsi-A_ikonas_-09.svg"},{"name":"Uzkodas","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/10\/Virsi-A_ikonas_-10.svg"},{"name":"Auto mazg\u0101tavu","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/11\/Virsi-A_ikonas_-11.svg"},{"name":"Pay with cards","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/12\/Virsi-A_ikonas_-12.svg"},{"name":"WiFi","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/13\/Virsi-A_ikonas_-13.svg"},{"name":"Gaiss","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/14\/Virsi-A_ikonas_-14.svg"},{"name":"\u016adens","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/16\/Virsi-A_ikonas_-16.svg"}]","data-lng":"24.11661410145257","data-lat":"56.997606561496724","children":[
                  {"tag":"span","class":"title","html":"DUS "Sarkandaugava""}
                ]}
            ]},
          {"tag":"li","class":"dus__list__item dus__list__item--40","children":[
              {"tag":"a","class":"map-link","id":"dus_40","href":"http://www.virsia.lv/lv/uzpildes-stacijas/#dus/40","data-contacts":""Kalngali", Sērenes pagasts, Jaunjelgavas novads, LV-5123<br ></a>
Tālr.: +371 65128121<br />
Darba laiks: 00:00 - 24:00<br />
","data-fuels":"[{"name":"95E","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/1\/Virsi-A_ikonas_-01.svg"},{"name":"DD","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/3\/Virsi-A_ikonas_-03.svg"},{"name":"AD","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/4\/Virsi-A_ikonas_-04.svg"},{"name":"G","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/5\/Virsi-A_ikonas_-06.svg"},{"name":"AD Blue","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/6\/Virsi-A_ikonas_-05.svg"},{"name":"WC","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/7\/Virsi-A_ikonas_-07.svg"},{"name":"Veikals","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/8\/Virsi-A_ikonas_-08.svg"},{"name":"Kafija","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/9\/Virsi-A_ikonas_-09.svg"},{"name":"Uzkodas","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/10\/Virsi-A_ikonas_-10.svg"},{"name":"WiFi","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/13\/Virsi-A_ikonas_-13.svg"},{"name":"Gaiss","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/14\/Virsi-A_ikonas_-14.svg"},{"name":"\u016adens","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/16\/Virsi-A_ikonas_-16.svg"},{"name":"Piekabju noma","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/17\/Virsi-A_ikonas_-17.svg"}]","data-lng":"25.22598270000003","data-lat":"56.57379109999999","children":[
                  {"tag":"span","class":"title","html":"DUS "Sērene""}
                ]}
            ]},
          {"tag":"li","class":"dus__list__item dus__list__item--41","children":[
              {"tag":"a","class":"map-link","id":"dus_20","href":"http://www.virsia.lv/lv/uzpildes-stacijas/#dus/20","data-contacts":"Zemkopības institūts 2a, Skrīveri, LV-5125<br ></a>
Tālr.:+371 65197262<br />
Darba laiks: 00:00 - 24:00<br />
","data-fuels":"[{"name":"95E","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/1\/Virsi-A_ikonas_-01.svg"},{"name":"98","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/2\/Virsi-A_ikonas_-02.svg"},{"name":"DD","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/3\/Virsi-A_ikonas_-03.svg"},{"name":"G","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/5\/Virsi-A_ikonas_-06.svg"},{"name":"AD Blue","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/6\/Virsi-A_ikonas_-05.svg"},{"name":"WC","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/7\/Virsi-A_ikonas_-07.svg"},{"name":"Veikals","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/8\/Virsi-A_ikonas_-08.svg"},{"name":"Kafija","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/9\/Virsi-A_ikonas_-09.svg"},{"name":"Uzkodas","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/10\/Virsi-A_ikonas_-10.svg"},{"name":"Auto mazg\u0101tavu","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/11\/Virsi-A_ikonas_-11.svg"},{"name":"WiFi","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/13\/Virsi-A_ikonas_-13.svg"},{"name":"Gaiss","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/14\/Virsi-A_ikonas_-14.svg"},{"name":"\u016adens","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/16\/Virsi-A_ikonas_-16.svg"},{"name":"Cash","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/18\/Virsi-A_ikonas_-18.svg"}]","data-lng":"25.11975849999999","data-lat":"56.6280997","children":[
                  {"tag":"span","class":"title","html":"DUS " Skrīveri""}
                ]}
            ]},
          {"tag":"li","class":"dus__list__item dus__list__item--42","children":[
              {"tag":"a","class":"map-link","id":"dus_21","href":"http://www.virsia.lv/lv/uzpildes-stacijas/#dus/21","data-contacts":"Stacijas iela 2, Smiltene, LV-4729<br ></a>
Tālr.:+371 64707266<br />
Darba laiks: 00:00 - 24:00<br />
","data-fuels":"[{"name":"95E","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/1\/Virsi-A_ikonas_-01.svg"},{"name":"98","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/2\/Virsi-A_ikonas_-02.svg"},{"name":"DD","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/3\/Virsi-A_ikonas_-03.svg"},{"name":"AD","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/4\/Virsi-A_ikonas_-04.svg"},{"name":"AD Blue","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/6\/Virsi-A_ikonas_-05.svg"},{"name":"WC","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/7\/Virsi-A_ikonas_-07.svg"},{"name":"Veikals","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/8\/Virsi-A_ikonas_-08.svg"},{"name":"Kafija","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/9\/Virsi-A_ikonas_-09.svg"},{"name":"Uzkodas","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/10\/Virsi-A_ikonas_-10.svg"},{"name":"WiFi","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/13\/Virsi-A_ikonas_-13.svg"},{"name":"Gaiss","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/14\/Virsi-A_ikonas_-14.svg"},{"name":"\u016adens","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/16\/Virsi-A_ikonas_-16.svg"},{"name":"Piekabju noma","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/17\/Virsi-A_ikonas_-17.svg"},{"name":"Cash","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/18\/Virsi-A_ikonas_-18.svg"}]","data-lng":"25.898199100000056","data-lat":"57.4279389","children":[
                  {"tag":"span","class":"title","html":"DUS "Smiltene""}
                ]}
            ]},
          {"tag":"li","class":"dus__list__item dus__list__item--1","children":[
              {"tag":"a","class":"map-link","id":"dus_52","href":"http://www.virsia.lv/lv/uzpildes-stacijas/#dus/52","data-contacts":"Vienības gatve 177, Rīga, LV-1058<br ></a>
Darba laiks: 00:00 - 24:00<br />
","data-fuels":"[{"name":"DD","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/3\/Virsi-A_ikonas_-03.svg"},{"name":"Pay with cards","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/12\/Virsi-A_ikonas_-12.svg"}]","data-lng":"24.081274500000063","data-lat":"56.90353469999999","children":[
                  {"tag":"span","class":"title","html":"ADDUS "Tīraine""}
                ]}
            ]},
          {"tag":"li","class":"dus__list__item dus__list__item--43","children":[
              {"tag":"a","class":"map-link","id":"dus_22","href":"http://www.virsia.lv/lv/uzpildes-stacijas/#dus/22","data-contacts":""Grodi", Tirzas pagasts, Gulbenes novads, LV-4424<br ></a>
Tālr.:+371 64472717<br />
Darba laiks: 06:00 - 23:00<br />
 ","data-fuels":"[{"name":"95E","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/1\/Virsi-A_ikonas_-01.svg"},{"name":"DD","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/3\/Virsi-A_ikonas_-03.svg"},{"name":"AD","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/4\/Virsi-A_ikonas_-04.svg"},{"name":"WC","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/7\/Virsi-A_ikonas_-07.svg"},{"name":"Veikals","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/8\/Virsi-A_ikonas_-08.svg"},{"name":"Kafija","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/9\/Virsi-A_ikonas_-09.svg"},{"name":"WiFi","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/13\/Virsi-A_ikonas_-13.svg"},{"name":"\u016adens","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/16\/Virsi-A_ikonas_-16.svg"}]","data-lng":"26.41039479999995","data-lat":"57.13861009999999","children":[
                  {"tag":"span","class":"title","html":"DUS "Tirza""}
                ]}
            ]},
          {"tag":"li","class":"dus__list__item dus__list__item--44","children":[
              {"tag":"a","class":"map-link","id":"dus_41","href":"http://www.virsia.lv/lv/uzpildes-stacijas/#dus/41","data-contacts":"Kurzemes iela 55, Tukums, LV-3101<br ></a>
Tālr.:+371 63125605<br />
Darba laiks: 00:00 - 24:00","data-fuels":"[{"name":"95E","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/1\/Virsi-A_ikonas_-01.svg"},{"name":"98","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/2\/Virsi-A_ikonas_-02.svg"},{"name":"DD","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/3\/Virsi-A_ikonas_-03.svg"},{"name":"AD","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/4\/Virsi-A_ikonas_-04.svg"},{"name":"WC","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/7\/Virsi-A_ikonas_-07.svg"},{"name":"Veikals","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/8\/Virsi-A_ikonas_-08.svg"},{"name":"Kafija","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/9\/Virsi-A_ikonas_-09.svg"},{"name":"Uzkodas","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/10\/Virsi-A_ikonas_-10.svg"},{"name":"WiFi","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/13\/Virsi-A_ikonas_-13.svg"},{"name":"Gaiss","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/14\/Virsi-A_ikonas_-14.svg"},{"name":"\u016adens","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/16\/Virsi-A_ikonas_-16.svg"},{"name":"Piekabju noma","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/17\/Virsi-A_ikonas_-17.svg"}]","data-lng":"23.138144900000043","data-lat":"56.9708456","children":[
                  {"tag":"span","class":"title","html":"DUS "Tukums""}
                ]}
            ]},
          {"tag":"li","class":"dus__list__item dus__list__item--44","children":[
              {"tag":"a","class":"map-link","id":"dus_42","href":"http://www.virsia.lv/lv/uzpildes-stacijas/#dus/42","data-contacts":""Valdaiši", Smārdes pagasts, Engures novads, LV-3129<br ></a>
Tālr.:+371 63120061<br />
Darba laiks: 00:00 - 24:00<br />
","data-fuels":"[{"name":"95E","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/1\/Virsi-A_ikonas_-01.svg"},{"name":"DD","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/3\/Virsi-A_ikonas_-03.svg"},{"name":"AD","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/4\/Virsi-A_ikonas_-04.svg"},{"name":"AD Blue","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/6\/Virsi-A_ikonas_-05.svg"},{"name":"WC","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/7\/Virsi-A_ikonas_-07.svg"},{"name":"Veikals","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/8\/Virsi-A_ikonas_-08.svg"},{"name":"Kafija","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/9\/Virsi-A_ikonas_-09.svg"},{"name":"Uzkodas","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/10\/Virsi-A_ikonas_-10.svg"},{"name":"WiFi","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/13\/Virsi-A_ikonas_-13.svg"},{"name":"Gaiss","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/14\/Virsi-A_ikonas_-14.svg"},{"name":"\u016adens","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/16\/Virsi-A_ikonas_-16.svg"},{"name":"Piekabju noma","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/17\/Virsi-A_ikonas_-17.svg"}]","data-lng":"23.20276699259034","data-lat":"56.933193545272104","children":[
                  {"tag":"span","class":"title","html":"DUS "Tukums Valdaiši""}
                ]}
            ]},
          {"tag":"li","class":"dus__list__item dus__list__item--7","children":[
              {"tag":"a","class":"map-link","id":"dus_58","href":"http://www.virsia.lv/lv/uzpildes-stacijas/#dus/58","data-contacts":""Avenes", Ugāle, Ugāles pagasts, Ventspils novads, LV-3615<br ></a>
Tālr.:+371 63621278<br />
Darba laiks: 06:00 - 23:00","data-fuels":"[{"name":"95E","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/1\/Virsi-A_ikonas_-01.svg"},{"name":"DD","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/3\/Virsi-A_ikonas_-03.svg"},{"name":"AD","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/4\/Virsi-A_ikonas_-04.svg"},{"name":"WC","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/7\/Virsi-A_ikonas_-07.svg"},{"name":"Veikals","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/8\/Virsi-A_ikonas_-08.svg"},{"name":"Kafija","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/9\/Virsi-A_ikonas_-09.svg"},{"name":"Uzkodas","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/10\/Virsi-A_ikonas_-10.svg"},{"name":"Gaiss","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/14\/Virsi-A_ikonas_-14.svg"},{"name":"\u016adens","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/16\/Virsi-A_ikonas_-16.svg"}]","data-lng":"22.019528100000002","data-lat":"57.2726853","children":[
                  {"tag":"span","class":"title","html":"DUS "Ugāle""}
                ]}
            ]},
          {"tag":"li","class":"dus__list__item dus__list__item--1","children":[
              {"tag":"a","class":"map-link","id":"dus_53","href":"http://www.virsia.lv/lv/uzpildes-stacijas/#dus/53","data-contacts":"Uriekstes iela 12a, Rīga, LV-1005<br ></a>
Darba laiks: 00:00 - 24:00<br />
","data-fuels":"[{"name":"DD","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/3\/Virsi-A_ikonas_-03.svg"},{"name":"Pay with cards","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/12\/Virsi-A_ikonas_-12.svg"}]","data-lng":"24.115602399999943","data-lat":"56.9932226","children":[
                  {"tag":"span","class":"title","html":"ADDUS "Uriekstes""}
                ]}
            ]},
          {"tag":"li","class":"dus__list__item dus__list__item--47","children":[
              {"tag":"a","class":"map-link","id":"dus_23","href":"http://www.virsia.lv/lv/uzpildes-stacijas/#dus/23","data-contacts":"Rūjienas iela 7, Valka, LV-4701<br ></a>
Tālr.:+371 64724106<br />
Darba laiks: 00:00 - 24:00<br />
","data-fuels":"[{"name":"95E","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/1\/Virsi-A_ikonas_-01.svg"},{"name":"98","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/2\/Virsi-A_ikonas_-02.svg"},{"name":"DD","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/3\/Virsi-A_ikonas_-03.svg"},{"name":"AD","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/4\/Virsi-A_ikonas_-04.svg"},{"name":"WC","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/7\/Virsi-A_ikonas_-07.svg"},{"name":"Veikals","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/8\/Virsi-A_ikonas_-08.svg"},{"name":"Kafija","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/9\/Virsi-A_ikonas_-09.svg"},{"name":"Uzkodas","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/10\/Virsi-A_ikonas_-10.svg"},{"name":"WiFi","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/13\/Virsi-A_ikonas_-13.svg"},{"name":"Gaiss","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/14\/Virsi-A_ikonas_-14.svg"},{"name":"\u016adens","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/16\/Virsi-A_ikonas_-16.svg"},{"name":"Piekabju noma","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/17\/Virsi-A_ikonas_-17.svg"}]","data-lng":"26.01809149999997","data-lat":"57.7873303","children":[
                  {"tag":"span","class":"title","html":"DUS "Valka""}
                ]}
            ]},
          {"tag":"li","class":"dus__list__item dus__list__item--47","children":[
              {"tag":"a","class":"map-link","id":"dus_24","href":"http://www.virsia.lv/lv/uzpildes-stacijas/#dus/24","data-contacts":"Rīgas iela 80, Valka, LV-4701<br ></a>
Tālr.:+371 64723802<br />
Darba laiks: 00:00 - 24:00<br />
","data-fuels":"[{"name":"95E","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/1\/Virsi-A_ikonas_-01.svg"},{"name":"DD","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/3\/Virsi-A_ikonas_-03.svg"},{"name":"AD","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/4\/Virsi-A_ikonas_-04.svg"},{"name":"WC","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/7\/Virsi-A_ikonas_-07.svg"},{"name":"Veikals","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/8\/Virsi-A_ikonas_-08.svg"},{"name":"Kafija","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/9\/Virsi-A_ikonas_-09.svg"},{"name":"Uzkodas","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/10\/Virsi-A_ikonas_-10.svg"},{"name":"WiFi","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/13\/Virsi-A_ikonas_-13.svg"},{"name":"Gaiss","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/14\/Virsi-A_ikonas_-14.svg"},{"name":"\u016adens","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/16\/Virsi-A_ikonas_-16.svg"}]","data-lng":"25.98717720000002","data-lat":"57.7590852","children":[
                  {"tag":"span","class":"title","html":"DUS "Valka Lugaži""}
                ]}
            ]},
          {"tag":"li","class":"dus__list__item dus__list__item--48","children":[
              {"tag":"a","class":"map-link","id":"dus_43","href":"http://www.virsia.lv/lv/uzpildes-stacijas/#dus/43","data-contacts":""Melderi", Valles pagasts, Vecumnieku novads, LV-5106<br ></a>
Tālr.:+371 65152883<br />
Darba laiks: 00:00 - 24:00<br />
","data-fuels":"[{"name":"95E","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/1\/Virsi-A_ikonas_-01.svg"},{"name":"DD","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/3\/Virsi-A_ikonas_-03.svg"},{"name":"AD","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/4\/Virsi-A_ikonas_-04.svg"},{"name":"WC","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/7\/Virsi-A_ikonas_-07.svg"},{"name":"Veikals","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/8\/Virsi-A_ikonas_-08.svg"},{"name":"Kafija","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/9\/Virsi-A_ikonas_-09.svg"},{"name":"Uzkodas","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/10\/Virsi-A_ikonas_-10.svg"},{"name":"WiFi","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/13\/Virsi-A_ikonas_-13.svg"},{"name":"Gaiss","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/14\/Virsi-A_ikonas_-14.svg"},{"name":"\u016adens","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/16\/Virsi-A_ikonas_-16.svg"},{"name":"Piekabju noma","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/17\/Virsi-A_ikonas_-17.svg"}]","data-lng":"24.72272780000003","data-lat":"56.5102132","children":[
                  {"tag":"span","class":"title","html":"DUS "Valle""}
                ]}
            ]},
          {"tag":"li","class":"dus__list__item dus__list__item--49","children":[
              {"tag":"a","class":"map-link","id":"dus_25","href":"http://www.virsia.lv/lv/uzpildes-stacijas/#dus/25","data-contacts":"Patversmes iela 12, Valmiera, LV-4201<br ></a>
Tālr.:+371 64224388<br />
Darba laiks: 06:00 - 23:00<br />
","data-fuels":"[{"name":"95E","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/1\/Virsi-A_ikonas_-01.svg"},{"name":"98","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/2\/Virsi-A_ikonas_-02.svg"},{"name":"DD","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/3\/Virsi-A_ikonas_-03.svg"},{"name":"AD","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/4\/Virsi-A_ikonas_-04.svg"},{"name":"WC","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/7\/Virsi-A_ikonas_-07.svg"},{"name":"Veikals","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/8\/Virsi-A_ikonas_-08.svg"},{"name":"Kafija","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/9\/Virsi-A_ikonas_-09.svg"},{"name":"WiFi","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/13\/Virsi-A_ikonas_-13.svg"},{"name":"Gaiss","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/14\/Virsi-A_ikonas_-14.svg"},{"name":"\u016adens","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/16\/Virsi-A_ikonas_-16.svg"},{"name":"Cash","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/18\/Virsi-A_ikonas_-18.svg"}]","data-lng":"25.395157700000027","data-lat":"57.5469794","children":[
                  {"tag":"span","class":"title","html":"DUS "Valmiera""}
                ]}
            ]},
          {"tag":"li","class":"dus__list__item dus__list__item--2","children":[
              {"tag":"a","class":"map-link","id":"dus_57","href":"http://www.virsia.lv/lv/uzpildes-stacijas/#dus/57","data-contacts":"Robežu iela 1, Ventspils, LV-3601<br ></a>
Tālr.: +371 63681016<br />
Darba laiks: 00:00 - 24:00","data-fuels":"[{"name":"95E","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/1\/Virsi-A_ikonas_-01.svg"},{"name":"98","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/2\/Virsi-A_ikonas_-02.svg"},{"name":"DD","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/3\/Virsi-A_ikonas_-03.svg"},{"name":"AD","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/4\/Virsi-A_ikonas_-04.svg"},{"name":"G","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/5\/Virsi-A_ikonas_-06.svg"},{"name":"AD Blue","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/6\/Virsi-A_ikonas_-05.svg"},{"name":"WC","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/7\/Virsi-A_ikonas_-07.svg"},{"name":"Veikals","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/8\/Virsi-A_ikonas_-08.svg"},{"name":"Kafija","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/9\/Virsi-A_ikonas_-09.svg"},{"name":"Uzkodas","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/10\/Virsi-A_ikonas_-10.svg"},{"name":"WiFi","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/13\/Virsi-A_ikonas_-13.svg"},{"name":"Gaiss","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/14\/Virsi-A_ikonas_-14.svg"},{"name":"\u016adens","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/16\/Virsi-A_ikonas_-16.svg"},{"name":"Piekabju noma","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/17\/Virsi-A_ikonas_-17.svg"}]","data-lng":"21.61489879999999","data-lat":"57.39458500000001","children":[
                  {"tag":"span","class":"title","html":"DUS "Ventspils""}
                ]}
            ]},
          {"tag":"li","class":"dus__list__item dus__list__item--21","children":[
              {"tag":"a","class":"map-link","id":"dus_26","href":"http://www.virsia.lv/lv/uzpildes-stacijas/#dus/26","data-contacts":"Kalna iela 19, Aizkraukle, LV-5101<br ></a>
Tālr.:+371 65133662<br />
Darba laiks: 06:00 - 23:00<br />
","data-fuels":"[{"name":"95E","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/1\/Virsi-A_ikonas_-01.svg"},{"name":"98","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/2\/Virsi-A_ikonas_-02.svg"},{"name":"DD","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/3\/Virsi-A_ikonas_-03.svg"},{"name":"AD","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/4\/Virsi-A_ikonas_-04.svg"},{"name":"Kafija","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/9\/Virsi-A_ikonas_-09.svg"},{"name":"Gaiss","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/14\/Virsi-A_ikonas_-14.svg"},{"name":"\u016adens","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/16\/Virsi-A_ikonas_-16.svg"}]","data-lng":"25.23597940000002","data-lat":"56.61521519999999","children":[
                  {"tag":"span","class":"title","html":"DUS "Virši""}
                ]}
            ]},
          {"tag":"li","class":"dus__list__item dus__list__item--22","children":[
              {"tag":"a","class":"map-link","id":"dus_27","href":"http://www.virsia.lv/lv/uzpildes-stacijas/#dus/27","data-contacts":""Katrīnkalns-1", Drabešu pagasts, Amatas novads, LV-4140<br ></a>
Tālr.:+371 64122448<br />
Darba laiks: 06:00 - 23:00<br />
","data-fuels":"[{"name":"95E","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/1\/Virsi-A_ikonas_-01.svg"},{"name":"DD","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/3\/Virsi-A_ikonas_-03.svg"},{"name":"AD","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/4\/Virsi-A_ikonas_-04.svg"},{"name":"WC","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/7\/Virsi-A_ikonas_-07.svg"},{"name":"Veikals","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/8\/Virsi-A_ikonas_-08.svg"},{"name":"Kafija","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/9\/Virsi-A_ikonas_-09.svg"},{"name":"Uzkodas","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/10\/Virsi-A_ikonas_-10.svg"},{"name":"WiFi","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/13\/Virsi-A_ikonas_-13.svg"},{"name":"Gaiss","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/14\/Virsi-A_ikonas_-14.svg"},{"name":"\u016adens","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/16\/Virsi-A_ikonas_-16.svg"},{"name":"Cash","image_url":"http:\/\/www.virsia.lv\/files\/vFuelType\/18\/Virsi-A_ikonas_-18.svg"}]","data-lng":"25.265709499999957","data-lat":"57.2955686","children":[
                  {"tag":"span","class":"title","html":"DUS "Žagarkalns""}
                ]}
            ]}
        ]}
    ]},
  {"tag":"div","class":"clear","html":""}
];